repos:
  - repo: local
    hooks:
      - id: black
        name: Format code with black
        entry: bash -c 'black "$@"; git add -u' --
        args: ["--verbose", "src"]
        language: python
        files: ^src/.*\.py$