# Taken from https://github.com/py-cov-action/python-coverage-comment-action?tab=readme-ov-file#basic-usage-without-external-contributors

name: CI

on:
  pull_request:
  push:
    branches:
      - "main"
      - "dev"

jobs:
  test:
    name: Run tests & display coverage
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install basic dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install package
        run: |
          pip install .

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage xml

      - name: Check code formatting with black
        run: black --check --diff src tests frontend

      - name: Coverage comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
