name: Coverage

permissions:
  contents: read
  pull-requests: write

on:
    push:
        branches:
        - main
        - dev
    pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install pytest pytest-cov

      - name: Run test & build coverage report
        run: |
          pytest \
            --cov=peptidefeatures \
            --cov-report=xml \
            --cov-report=json:coverage.json

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.json

  comment:
    needs: test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download coverage.json
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: .
      - name: Comment coverage report
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: coverage.json
