name: Coverage

on:
    push:
      branches:
        - main
        - dev
    pull_request: {}

jobs:
    coverage-comment:
        name: Comment coverage report
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
        - uses: actions/checkout@v3

        - name: Download coverage artifact
          uses: actions/download-artifact@v4
          with:
            name: coverage-report
            path: .
        - name: Comment coverage in PR
          uses: py-cov-action/python-coverage-comment-action@v3
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
